### ISSUE TITLE
Requirements are very tight

### ISSUE THREAD

**Issue by bmxp** [orcasgit/python-nokia#26]
Hey guys,
I wonder why your requirements are so tight? I mean is there a reason to fence in requests or cherrypy? If so please write it down otherwise it would be nice if you loose it more so the lib would less probably collide with other modules...

**Comment by psilo909** [comment]
i agree to @bmxp 

we are currently using the lib in our software SmartHomeNG and we are not limiting cherrypy and requests to the most recent level, as long as we dont find real incompatibilities. 

we implemented a complex webbased requirements check into our software and would need to set the very strict requirements of nokia lib explcitly in my plugin. so i also wonder of the tight requirements (at least to the newest version) really make sense here?

**Comment by brad** [comment]
@bmxp There is no reason, we are happy to accept PRs changing this.

**Comment by bmxp** [comment]
@psilo909 Since you are using the plugin in SmartHomeNG and thus this lib, could you find out if there are incompatablities with the latest requests and cherrypy versions?

**Comment by bmxp** [comment]
@psilo909 Did you encounter any further problems or could we think about closing this issue?

**Comment by psilo909** [comment]
@bmxp i did not encounter problems concerning requests (I am using 2.22.0), but have problems concerning the related oauth libraries. 
in any way i will not take responsibility on doing a PR here modifiying their original requirements, even though the development on this library here is not really active.. lets close it and keep it the way it is.

**Comment by psilo909** [comment]
I also just saw in summer they modified the requirements to less restrictive ones: https://github.com/orcasgit/python-nokia/blob/master/requirements/base.txt

in fact cherrypy is still restrictive. this may be the case for the whole code here. as i am doing my own webinterface in SHNG, i think the cherrypy requirement is obsolete for our integration!
