### ISSUE TITLE
New release of 1.2.1? Home assistant is broken without this release.

### ISSUE THREAD

**Issue by vangorra** [orcasgit/python-nokia#38]
Look like the withings API requires the client_id when calling get_credentials(self, code). Shortly after the 1.2.0 release a commit was added that addresses this issue. (https://github.com/orcasgit/python-nokia/commit/d929914cb92f685c9c8ac4a810b2e3afe127068b)

Can we get a new release and version bump? This is causing issues with upstream dependencies. Specifically with home assistant. https://github.com/home-assistant/home-assistant/issues/26716

**Comment by sjabby** [comment]
@brad ? 😁😁

**Comment by Bluhme1** [comment]
@brad @orcas Is development of this halted or can we expect a solution soon?

**Comment by Bluhme1** [comment]
@vangorra Hello Vangorra. Is there anything we can do to make the requested changes happen? Or is there a way to do without it and still have access to the API.
I have your files in custom_components and have made the work-around from Skeletorjus, so everything works here. Perhaps I should just leave it there?

**Comment by brad** [comment]
@vangorra @sjabby @Bluhme1 Hey all. Yes, development is halted on this. You will either need to fork and publish your own pip package, or `pip install https://github.com/orcasgit/python-nokia`

**Comment by vangorra** [comment]
Okay. I'll fork the project this weekend.

**Comment by Bluhme1** [comment]
@vangorra. Great. How do we install the new library?

**Comment by vangorra** [comment]
Project forked. Now I need to integrate with home assistant. https://github.com/vangorra/python_withings_api
