### ISSUE TITLE
What Is The Official Withings Python Module To Use That Is Supported?

### ISSUE THREAD

**Issue by jeangv** [orcasgit/python-nokia#42]
What Is The Official Withings Python Module To Use That Is Supported?

I was hoping somebody could help me understand this better. I am looking to interface with the Withings API, for the Withings bathroom scales. I have been using the Python module called “Nokia”, but it has not been updated in some time. Is there an “official” Withings Python module that should be used instead? 

Here are 3 Withings modules I have found. Is there an “official” or preferred one to code with? 

- [**withings**](https://github.com/maximebf/python-withings)
- [**withings-api**](https://github.com/vangorra/python_withings_api)
- [**nokia**](https://github.com/orcasgit/python-nokia)

Thanks for any help! 
Jean-Marie Vaneskahian 
jean@vaneskahian.com
(January 31st, 2021)

**Comment by psilo909** [comment]
@jeangv I just migrated from the nokia thing here (which caused horrible requirement conflicts in our smart home framework -> https://github.com/orcasgit/python-nokia/issues/26) to withings-api. So far all fine for that. Even the migration was pretty easy. 

For my integration see https://github.com/smarthomeNG/plugins/tree/master/withings_health

withings (your first one) looks extremely outdated with the last commit 6 years ago.. I think at this point in time, even the oauth authentification was not present.

I think "official" is nothing, as all are open source projects. but withings-api seems the most mature and actively developed one.

**Comment by jeangv** [comment]
@psilo909 Thanks so very much for the reply! I will look into migrating from the Nokia module that I am currently using to the withings-api module instead. I hope that they are similar in how they store authentication data so that I do not have to start over and get the OAuth token since I already have that from Nokia. My hope is that I can keep going with my existing refresh and access tokens.

On a side note, I see comments on your smarthomeNG that the "tokens expire"... while that is true if you use the access token and then do not refresh it... What I do is I store both the access token and refresh token in a SQL DB. When I am going to make a call for data I update the keys by do a update_keys before I make the API call and again after. This way I have been able to go months and never had the refresh token expire (apparently it expires in 4 hours if you use it, but not if you don't). With each call for a new access token you also get a new refresh token. Hope this makes sense.

```
def update_keys(withings_api_keys):
    withings_url = "https://account.withings.com/oauth2/token"
    post_data = {"grant_type": "refresh_token", "client_id": withings_api_keys["client_id"], "client_secret": withings_api_keys["consumer_secret"], "refresh_token": withings_api_keys["refresh_token"]}
    response = requests.post(url=withings_url, data=post_data)
    json_data = json.loads(response.text)
    withings_api_keys["access_token"] = json_data["access_token"]
    withings_api_keys["refresh_token"] = json_data["refresh_token"]
    return withings_api_keys
```

Thanks again for your help!

**Comment by psilo909** [comment]
Hi @jeangv,

I am also storing the tokens (and the renewed token) in our item structure: https://github.com/smarthomeNG/plugins/blob/master/withings_health/__init__.py#L59
and
https://github.com/smarthomeNG/plugins/blob/master/withings_health/__init__.py#L119
This is way its literally working "forever".

However when developing our framework, sometimes the downtime is longer than the expiry time for the token. In these cases I have to start the retrieval process again manually.. But its done in 10 sec from our web interface. So its no big deal.
